version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: backendtest
      MYSQL_PASSWORD: ""
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
#     networks:
#       - app-network

#   node-be:
#     #build: ./node-be
#     image: node:14.15.4-alpine3.12
#     container_name: node-be
#     restart: unless-stopped
#     command: sh -c "npm install && npm run start"
#     depends_on:
#        - mysql
#     tty: true
#     environment:
#        MYSQL_HOST: mysql
#        MYSQL_USER: root
#        MYSQL_PASSWORD: ""
#        MYSQL_DB: backendtest
#        MYSQL_PORT: 3306
#     ports:
#        - 8000:8000
#     volumes:
#        - ./node-be:/usr/src/app
#        - /usr/src/app/node_modules
#     networks:
#        - app-network

# networks:
#   app-network:

